run-name: ${{ github.actor }} New Release la Manu Test
on:
  push:
    tags:
      - '*'
jobs:
  commandls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "apt update image non modifiable"
      - run: ls
      - run: systemd-detect-virt  
      - run: env 
      - run: python main.py
      - uses: ncipollo/release-action@v1
        with:
        artifacts: "release.tar.gz,dossier/*.txt"
        bodyFile: "body.md"
