run-name: ${{ github.actor }} for la Manu Test
on: [push]
jobs:
  commandls :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "apt update image non modifiable"  
      - run: ls 
      - run: python main.py

