run-name: ${{ github.actor }} New Release la Manu Test
on:
  push:
    tags:
      - '*'
jobs:
  new_release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "apt update image non modifiable"
      - run: ls
      - run: systemd-detect-virt
      - run: env
      - run: python main.py
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release.tar.gz,dossier/*.txt"
          bodyFile: "body.md"
